pr:
  - master
  - develop
  
trigger:
  - master
  - develop

pool:
  name: Hosted Ubuntu 1604

variables:
  ProjectID: "spqlr1x2iywwy3df3ifsx84mol83c2"
  DockerImageName: "$(ProjectID)/cert-manager-webhook-dyndns"

jobs:
  - job: DockerBuild
    steps:
    - task: Docker@2
      displayName: Login to GCR
      inputs:
        containerRegistry: 'novos-produtos-sre-team-front'
        command: 'login'

    - task: Docker@2
      displayName: "Build and Push image"
      inputs:
        containerRegistry: 'novos-produtos-sre-team-front'
        repository: '$(DockerImageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest